# 指定运行端口
server:
  port: 8000

# 指定服务名称
spring:
  application:
    name: eureka-server

# 详见EurekaServerConfigBean，需要注意与Client和Instance在client的jar包不同，Server是在server的jar包。
eureka:
  # 修改Eureka监控页面的System Status Data center
  datacenter: dev
  # 修改Eureka监控页面的System Status Environment
  environment: dev
  instance:
    hostname: localhost
  client:
    # 默认情况下，eureka server同时也是eureka client，用于相互注册形成高可用eureka服务。
    # 单点时，如果registerWithEureka配置为true，则eureka server会报错Cannot execute request on any known server
   # eureka之间如果网络不稳定，客户端一般也会缓存了注册列表，因此eureka服务可以不缓存，我觉得更能确保eureka之间的一致。
    fetch-registry: false
    # 是否注册到eureka服务，默认为true，当前已为eureka server，且单点eureka，故配置为false
    register-with-eureka: false
    # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址
    service-url:
    # registerWithEureka关闭后，defaultZone没有配置的必要。如果打开，即使配置为本机一样报错。
    # 也就是说defaultZone任何时候都没有配置为localhost的必要。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
  server:
    # 自我保护机制，默认true。打开后，心跳失败在15分钟内低于85%(renewalPercentThreshold)的服务，也不进行剔除。
    # 关闭后，主页提示：RENEWALS ARE LESSER THAN THE THRESHOLD. THE SELF PRESERVATION MODE IS TURNED OFF.

    # 定时检查服务心跳，每隔两秒检测一次。默认60000ms
    # 启用主动失效，并且每次主动失效检测间隔为3s。
    # 需要注意的是该配置会打印INFO日志，增加info日志量，修改后从每60秒打印一次变成3秒打印一次。
    eviction-interval-timer-in-ms: 5000
    #关闭一级缓存，让客户端直接从二级缓存去读取，省去各缓存之间的同步的时间
    use-read-only-response-cache: false
    #过期服务保护。默认开启
    # 本地调试时可fasle关闭。但生产建议打开，可防止因网络不稳定等原因导致误剔除服务。
    enable-self-preservation: false
    # 默认85%
    renewal-percent-threshold: 0.85
    # eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    # 默认30秒，eclipse提示默认0应该是错误的，源代码中responseCacheUpdateIntervalMs = 30 * 1000。
    response-cache-update-interval-ms: 3000
    # eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，
    # 过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
    # 由于启用了evict其实就用不太上改这个配置了，默认180s
    response-cache-auto-expiration-in-seconds: 180
    # 在服务器接收请求之前等待的初始时间，默认等待5min（John Carnell）
    # John说开发时最好注释此配置，服务注册需要3次心跳，每次10s，也就是30s才能显示在eureka。但是为什么我这里马上就显示呢？
    wait-time-in-ms-when-sync-empty: 5








#eureka.server.enable-self-preservation=false
#eureka.server.responseCacheUpdateInvervalMs=3000
#eureka.server.responseCacheAutoExpirationInSeconds=5
#eureka.instance.lease-renewal-interval-in-seconds=1
#eureka.client.registryFetchIntervalSeconds=5
#ribbon.ServerListRefreshInterval=1000
#eureka.instance.preferIpAddress=true
#eureka.server.response-cache-update-interval-ms=3
#eureka.server.response-cache-auto-expiration-in-seconds=3
#eureka.server.use-read-only-response-cache=false