server:
  port: 8760

spring:
  application:
    name: COMMON-GATEWAY
    description: 微服务网关
    version: 1.0.0-SNAPSHOT
  cloud:
    gateway:
      routes:
#        - id: gateway-service0
#         # lb代表从注册中心获取服务
##         uri: lb://OLOAN-FINANCIAL-PRODUCT-SERVICE
#          uri: https://www.baidu.com
#          predicates:
#            - Path=/index
#          filters:
#            - StripPrefix=1

        - id: gateway-service1
          uri: lb://EXAMPLES-SPRINGBOOT
          predicates:
            - Path=/gateway/examples-springboot/**
          filters:
            - StripPrefix=2

        - id: gateway-service2
          uri: lb://EXAMPLE-CUSTOMER
          predicates:
             - Path=/gateway/example-customer/**
          filters:
             - StripPrefix=2
      discovery:
        locator:
          enabled: true

eureka:
   instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int[1,9]}}--${spring.application.version}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
   client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    registry-fetch-interval-seconds: 10

#actuator health check
management:
  health:
    redis:
      enabled: false
    db:
      enabled: false
  endpoint:
    health:
      show-details: always
      enabled: true
    httptrace:
      enabled: true

#actuator info
info:
  app:
    name:  ${spring.application.name}
    description: ${spring.application.description}
    version: ${spring.application.version}


