# 指定运行端口
server:
  port: 8760

# 指定服务名称
spring:
  application:
    name: common-gateway
    description: 微服务网关
    version: 1.0.0-SNAPSHOT
  cloud:
    gateway:
      routes:
       - id: gateway-service
         url: https://blog.csdn.net
         predicates:
          - Path=/index

eureka:
   instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int[1,9]}}--${project.version}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
   client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    registry-fetch-interval-seconds: 10

#actuator health check
management:
  health:
    redis:
      enabled: false
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
      enabled: true
    httptrace:
      enabled: true
  server:
    port: 8762

#actuator info
info:
  app:
    name:  ${spring.application.name}
    description: ${spring.application.description}
    version: ${spring.application.version}


