server:
  port: 9080

spring:
  application:
    name:  examples-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      # EurekaServer地址
      defaultZone: http://localhost:8000/eureka/
    #健康检测
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
   # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    prefer-ip-address: true
    # 指定自己的ip信息，不指定的话会自己寻找
    ip-address: 127.0.0.1
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）_开发配置
    lease-renewal-interval-in-seconds: 2
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）_开发配置
    lease-expiration-duration-in-seconds: 10

